### ISSUE TITLE
Does not compile on base 4.5

### ISSUE THREAD

**Issue by JustusAdam** [Happstack/happstack-server#14]
Library constraints in the .cabal file allow for base == 4 but it does not compile with 4.5 at least

```
Failed to install happstack-server-7.4.3
Last 10 lines of the build log ( /home/travis/.cabal/logs/happstack-server-7.4.3.log ):
                          or `Control.Monad.Catch.catch',
                             imported from `Control.Monad.Catch' at src/Happstack/Server/Internal/Monads.hs:11:52-65
src/Happstack/Server/Internal/Monads.hs:348:34:
    Ambiguous occurrence `catch'
    It could refer to either `Prelude.catch',
                             imported from `Prelude' at src/Happstack/Server/Internal/Monads.hs:4:8-39
                             (and originally defined in `System.IO.Error')
                          or `Control.Monad.Catch.catch',
                             imported from `Control.Monad.Catch' at src/Happstack/Server/Internal/Monads.hs:11:52-65
cabal: Error: some packages failed to install:
happstack-lite-7.3.6 depends on happstack-server-7.4.3 which failed to
install.
happstack-server-7.4.3 failed during the building phase. The exception was:
ExitFailure 1
```

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.4.2
```

I propose travis integration for this repository with testing against multiple ghc versions to ensure it works with the base library (as described inn [this](https://github.com/hvr/multi-ghc-travis) repository)

**Comment by stepcut** [comment]
There is an open pull request:

https://github.com/Happstack/happstack-server/pull/13

That just raises the minimum base version to 4.6. But perhaps we just need to hide the version from Prelude?

**Comment by JustusAdam** [comment]
It should work either way. I guess the question is do you want to stay compatible with < 4.6?

**Comment by stepcut** [comment]
I uploaded a new version which may work. I added an explicit import list for Prelude in that file which should avoid the name collision with out having to resort to #ifdefs for different versions of base.

Staying compatible with base < 4.6 is not a high priority, but this was an easy enough fix (assuming I fixed it) that I think it is worthwhile.

Putting the happstack family in some sort of continuous integration system is definitely something that should have been done a long time ago. I've recently been experimenting with Hydra and Nix. Right now I am only building against 7.10 -- but Nix appears to support GHC all the way back to 6.10.4. 

The primary advantage of Hydra over Travis-CI is that it builds packages which can then be deployed via NixOps. Having a single configuration that I use for building locally, building packages for deployment, and for doing continuous integration seems like the best way to ensure everything stays in sync with out having to do a bunch of duplicate work.

**Comment by JustusAdam** [comment]
Very nice. Do what you think works best. I mostly deal with smaller and singular projects so I don't really have to consider myself with duplicate work.

Do you have a way of testing the new build? Otherwise I'll do it.

**Comment by stepcut** [comment]
I have only tested with GHC 7.10. I do plan to setup automatic testing of multiple GHC versions eventually, but there are other higher priority things at the moment.

**Comment by stepcut** [comment]
happstack-server is now in travis-ci. I will start adding the others over time. https://travis-ci.org/Happstack/happstack-server. I've opted to only go as far back as 7.6.3 since 7.4.x is getting pretty old.

**Comment by JustusAdam** [comment]
Very good.
