### ISSUE TITLE
Filters that negoticate based on Content-Encoding should set Vary header

### ISSUE THREAD

**Issue by dcoutts** [Happstack/happstack-server#16]
According to (my reading of) the HTTP spec, changing the Content-Encoding is changing the entity (as opposed to the message transfer). So if a content encoding is negotiated (e.g. for compression via the Accept header) then caches need to know this because the representation of the entity is changing depending on which accept header the client sent. The way to inform caches of this is with the Vary header.

So for example, the `compressedResponseFilter` sets the `Content-Encoding` based on the `Accept` header, so it must set the header `Vary: Accept` so that intermediate caches can work properly.

I believe Apache's mod_deflate does this, so it's common practice not just spec lawyering. (If we were doing spec lawyering we'd say that we should never use `Content-Encoding` because it's part of the entity and that we should use `Transfter-Encoding` instead, but apparently common practise is to use  `Content-Encoding`. Ho hum.)

**Comment by stepcut** [comment]
I believe `Vary: Accept-Encoding` is even more correct.

https://www.fastly.com/blog/best-practices-for-using-the-vary-header

https://github.com/Happstack/happstack-server/commit/7cb2e31025de94ee0d62f897714c6ec106a4c70a
