### ISSUE TITLE
Support http PATCH methods?

### ISSUE THREAD

**Issue by jhedev** [Happstack/happstack-server#18]
While working on an RESTful API, I discovered that happstack does not support PATCH methods?

**Comment by stepcut** [comment]
That is true. happstack-server only supports the methods in the HTTP 1.1 spec and fails to support extension methods. This is not really a sound decision, and support for extensions really ought to be added. One question is whether PATCH should be treated like GET, POST, PUT, etc. Or if it should only be supported via,

    | EXTENSION Text

If PATCH is widely supported, then I'd favor making it a constructor, even though it is not part of the HTTP 1.1 spec.

**Comment by jhedev** [comment]
Snap (see [here](http://hackage.haskell.org/package/snap-core-0.9.8.0/docs/Snap-Core.html#t:Method)) and http-types (see [here](http://hackage.haskell.org/package/http-types-0.8.6/docs/Network-HTTP-Types-Method.html#t:StdMethod)), which is what `wai` uses, support it.

Other than that I'm not sure how widely this is used or supported.

**Comment by cyanistes** [comment]
This explains why there isn't already a todobackend for happstack.

**Comment by stepcut** [comment]
This will be patched in happstack-server-7.5. Because it requires an API bump it will be rolled in with some other minor changes to the API.

**Comment by jhedev** [comment]
Can confirm that it works, as I've implemented the todobackend: https://github.com/jhedev/todobackend-haskell/tree/master/todobackend-happstack

:+1:

**Comment by stepcut** [comment]
Awesome. This change requires a version bump before I upload it hackage, so I am bundling it which some other feature requests that required API changes. Should be on hackage in a day or two.
