### ISSUE TITLE
MonadPlus instance of ServerPartT

### ISSUE THREAD

**Issue by prophet-on-that** [Happstack/happstack-server#20]
Hi,

This issue seems to have existed since version 7.4.3, when the MonadPlus instance for ServerPartT changed from 
```haskell
Monad m => MonadPlus (ServerPartT m)
```
to
```haskell
MonadPlus m => MonadPlus (ServerPartT m)
```
As far as I can see, this makes the library unusable when using, for example, HappStack's routing functions (which require a MonadPlus instance), in even the base ServerPart monad.

Am I missing something here?

**Comment by stepcut** [comment]
Hello,

Can you give me an example of something that used to work, but no longer does? The examples in this section of the book still work fine for me:

    http://www.happstack.com/docs/crashcourse/index.html#route-filters

I am using `happstack-server-7.4.5` and `ghc-7.10.2`. Perhaps we have broken ghc-7.8.X compatibility?

**Comment by prophet-on-that** [comment]
Firstly, I didn't realise the transformers library exported a MonadPlus instance for IO, which is why I assumed a ServerPart example would break. I can successfully build the example in the book with `happstack-server-7.4.5`. 

Here's code which builds successfully with v7.3.9 but not with v7.4.5:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

module Test where

import Control.Monad
import Control.Applicative
import Happstack.Server
import Control.Monad.Reader

newtype ConnectionT m a = ConnectionT
  { unConnectionT :: ReaderT String m a
  } deriving (Functor, Applicative, Monad)

route :: ServerPartT (ConnectionT IO) String
route
  = msum
      [ dir "hello" $
          ok "hi"

      , dir "goodbye" $
          ok "goodbye"
      ]
```

This is because `ConnectionT IO` does not instantiate `MonadPlus`. This didn't used to be a problem because of the MonadPlus instance for ServerPartT. However, now that I realise `IO` does have a `MonadPlus` instance, I can simply derive `Alternative` and `MonadPlus` to solve my problem. 

Thanks anyway!
