### ISSUE TITLE
Happstack.com website is stalled

### ISSUE THREAD

**Issue by gbaz** [Happstack/happstack-server#38]
The error was "/home/jeremy/public_html/happstack-crashcourse/index.html: openBinaryFile: resource exhausted (Too many open files)"

Not sure where else to report it.

**Comment by stepcut** [comment]
Thanks for the report. It looks like when the server was moved to a new machine HsColour was not installed. Apparently this function leaks file descriptors when HsColour is missing,

https://github.com/clckwrks/clckwrks/blob/master/Clckwrks/Markup/HsColour.hs

I installed HsColour which should make the symptom disappear, though the code itself is still buggy.

**Comment by ksilin** [comment]
almost same error resurfaced today: `The error was "/home/jeremy/public_html/happstack-crashcourse: getDirectoryContents:openDirStream: resource exhausted (Too many open files)"`

**Comment by ksilin** [comment]
available again

**Comment by toovs** [comment]
down again?

**Comment by stepcut** [comment]
I believe the current downtime is due to a space leak in the irc plugin. I have disable that plugin and am waiting for a rebuild. Though I think the person who does that is currently traveling.

**Comment by marco-comini** [comment]
the site is not "technically" down, but home page of the happstack.com site is a "Apache2 Ubuntu Default Page" instead of the normal home page we expect. Also all the material, including the Crashcourse. Will all come back again, or it moved somewhere else?

**Comment by stepcut** [comment]
It should be back now. Just some boring sys-admin mishaps. Someone tried to upgrade some debian packages on that server and the happstack.com server packages got removed and never properly reinstalled.
