### ISSUE TITLE
HTTP request failed with: Network.Socket.sendBuf: resource vanished (Broken pipe)

### ISSUE THREAD

**Issue by jeffersoncarpenter** [Happstack/happstack-server#39]
Sorry for such a vague issue -- I am still very much in the process of debugging this and creating a minimal reproducible example.  It easily could be (in fact it probably is) a bug in my code or unrelated to Happstack.  This just seems to be the right place to put it, because it is an error that appears to be thrown from Happstack code.  Basically, here's the error message that I'm getting:

    HTTP request failed with: Network.Socket.sendBuf: resource vanished (Broken pipe)

This happens periodically, seemingly at random.

**Comment by stepcut** [comment]
Are there any other symptoms besides that error message? The HTTP specification allows the client to terminate the connection by just closing its end of the connection. That would result in the error message you are seeing. It is probably harmless. However, there could be other times when you get that message and it is not harmless -- so we have been reluctant to suppress the error entirely.

In summary, this may or may not be a bug in Happstack -- but unless you are seeing some other issue you should ignore it. Unless it really bothers you, in which case you should figure out if there is some way for us to distinguish between a bad close and a good close by the client. And then we can do a better job of showing this error message only when an error has truly occurred.

**Comment by jeffersoncarpenter** [comment]
> Are there any other symptoms besides that error message?

Yeah - the server actually stops responding to any requests whatsoever after a few hours.  It loads for around 30 seconds and then displays a generic Happstack error page.  I'll let you know as soon as I have more information.  I am continuing to narrow down on the exact cause.  It could be due to a failure with the running MySQL connection, not the HTTP connection, but I'm not sure.  There are actually more errors than just that one:

    UnexpectedPacket (Packet {pLen = 1, pSeqN = 1, pBody = "\SOH"})
    UnexpectedPacket (Packet {pLen = 49, pSeqN = 2, pBody = "\ETXdef\taoeu2code\acaptcha\acaptcha\STXid\STXid\f?\NUL\n\NUL\NUL\NUL\ETX#B\NUL\NUL\NUL"})
    UnexpectedPacket (Packet {pLen = 5, pSeqN = 4, pBody = "\EOT4030"})
    UnexpectedPacket (Packet {pLen = 1, pSeqN = 1, pBody = "\EOT"})

appear at the beginning of my error log, followed by a large number of `UnconsumedResultSet` errors as well as

    HTTP request failed with: Network.Socket.sendBuf: resource vanished (Broken pipe)

and

    HTTP request failed with: Network.Socket.recvBuf: resource vanished (Connection reset by peer)

.  So it's a combination of MySQL errors and Happstack ones.  Actually I'm pretty sure my MySQL connection is the root cause.  Sorry to bother you!  Feel free to close this issue -- or if you leave it open then I'll close it once I finally solve the problem with my site.

BTW, I think there are multiple problems with my site's code, another being my MVar usage.  The site creates a MySQL connection when it starts up, pings it to keep it alive in a forked thread, and also uses it to serve pages.  Before I added MVars, it would work for a few hours, then begin to serve my application's 500 error page.  I figured the database functions might not be thread-safe (the ping thread could be interfering with the HTTP requests - not to mention the possibility of concurrent HTTP requests), so I placed the database handle behind an MVar.  After doing that, after running for a few hours, it still stops serving requests correctly, but instead of serving my application's 500 page instantly, it serves Happstack's generic one after 30 seconds.

(It's possible I could "solve the problem" by connecting to the database inside each request instead of trying to keep a single database connection alive over the lifetime of the application, but for the sake of my sanity, I want to see the errors play out in a way that I can understand - and then connect to the database inside each request.)

**Comment by jeffersoncarpenter** [comment]
> The HTTP specification allows the client to terminate the connection by just closing its end of the connection. That would result in the error message you are seeing. It is probably harmless. However, there could be other times when you get that message and it is not harmless -- so we have been reluctant to suppress the error entirely.

That does seem to be the case.  That could be the cause of all of those errors I'm seeing.

> Unless it really bothers you, in which case you should figure out if there is some way for us to distinguish between a bad close and a good close by the client. And then we can do a better job of showing this error message only when an error has truly occurred.

It kind of does.  Is there such a thing as a "bad" close by a client - is there anything to distinguish?  If the client closes the connection, that is the client's problem is it not?

**Comment by jeffersoncarpenter** [comment]
For the record, I'm 99% sure I've solved the MVar component.  Basically I'm just falling for gotchas that an experienced Haskell developer would know to avoid.  Here are the gory details:

My database handle is shared by A) all request threads, and B) a forked thread that pings the database to keep it alive.  The forked thread (B) has type `IO ()` so naturally I used `withMVar` to check out the database handle, ping it, and return it.  The request threads (A) have type `ServerPart Response`, so I could not use `withMVar` -- I had to use `takeMVar` and `putMVar`.  I had tried to copy the code for `withMVar` but got it wrong.  I would check out the database connection, use it in my request handler, and then return it -- also returning it on exceptions thrown from the request handler.  What I did not account for was that the `mempty` value of `ServerPart Response` is not an exception, but also obeys the identity `mappend mempty x = x`, so the remainder of any do block in which an `mempty` value is produced is not executed.

Old code (again, basically copied from the `withMVar` implementation):

    app :: MVar MySQLConn -> ServerPart Response
    app mDB = do
      db <- liftIO $ takeMVar mDB
      response <- app' db `onException` (liftIO $ putMVar mDB db)
      liftIO $ putMVar mDB db
      return response

New code:

    app :: MVar MySQLConn -> ServerPart Response
    app mDB = do
      db <- liftIO $ takeMVar mDB
      response <- optional (app' db) `onException` (liftIO $ putMVar mDB db)
      liftIO $ putMVar mDB db
      fromMaybe mempty $ fmap return response

**Comment by jeffersoncarpenter** [comment]
Gonna go ahead and close this despite the possibility of hiding `HTTP request failed with: Network.Socket.sendBuf` errors.  If that is to be reported as an issue and fixed, it would be best done in a fresh thread.  Server has been running flawlessly since I fixed my MVar usage.  Thanks for your time and patience :)
