### ISSUE TITLE
Bump some dependency upper bounds 

### ISSUE THREAD

**Issue by YuMingLiao** [Happstack/happstack-server#44]
Hi, I wasn't sure how it works. I couldn't find happstack's github.
Could Happstack bump happstack-server dependency upper bounds since now happstack-server is 7.5.1.1?
Happstack still has a bound of happstack-server (>=7.0 && <7.4).

--

**Comment by stepcut** [comment]
The package `happstack` has been deprecated. All the stuff it used to contain got moved elsewhere. Now it just pulls into `happstack-server`. You probably just want to change your code to depend on `happstack-server` instead of `happstack` ?

**Comment by YuMingLiao** [comment]
hi @stepcut I see. Thank you for telling me that!
