### ISSUE TITLE
Update mime types list

### ISSUE THREAD

**Issue by PaulRivier** [Happstack/happstack-server#61]
Hi,

default mime-types list is very old, 10+ years old. In this old constant, for instance Javascript has associated type "application/x-javascript", which is deprecated and interferes with some HTTP tools, like compression, cache etc.  Function serveDirectory can not be parametrized with a custom types list, therefore serving static content such as JS files through this function will end-up with obsolete mime type and lack of compression.

Could you please update this list, and consider offering a parametrized serveDirectory for this situation. FWIW this package seems active : http://hackage.haskell.org/package/mime-types-0.1.0.9

Thank you very much, I really appreciate Happstack and your work.

**Comment by stepcut** [comment]
Good idea!

There is a parameterized `serveDirectory'` already,

https://github.com/Happstack/happstack-server/blob/master/src/Happstack/Server/FileServe/BuildingBlocks.hs#L700

Does that not do what you need?

**Comment by PaulRivier** [comment]
Hi Jeremy,

Indeed, serveDirectory' allowed me to keep going, with a custom mime list, good idea you had when you designed this part. In the end I did not use mime-types package, because of string-variants mismatch that was not worth it. Thank you for your reply, thank you very much for happstack.

**Comment by stepcut** [comment]
Just pushed two patches which update the mimeTypes function to use this list of mime-types,

http://svn.apache.org/viewvc/httpd/httpd/branches/2.4.x/docs/conf/mime.types?view=co

Hopefully that is a bit more up to date,

https://github.com/Happstack/happstack-server/commit/b6e333148dc1fffa192f070de80abd70ad114f0c

**Comment by stepcut** [comment]
This will be in happstack-server-7.6.0.

**Comment by PaulRivier** [comment]
Thank you very much.
