### ISSUE TITLE
network-3.2 not accepted

### ISSUE THREAD

**Issue by ysangkok** [Happstack/happstack-server#84]
It would be nice to accept this new version of the network library. See

* https://github.com/commercialhaskell/stackage/issues/7381

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/happstack-server-7.9.0/revisions/

**Comment by stepcut** [comment]
Thanks. I patched the `.cabal` in github last month, but did not upload it because until today(?) `network-bsd` was still keeping `network` pegged at 3.1 -- so I could not (easily) test the change. I will address the `xhtml` issues and upload a new version.

**Comment by ysangkok** [comment]
Closing this since it seems resolved everywhere except in happstack-server-tls which is a different repo with its own issue:

* https://github.com/Happstack/happstack-server-tls/issues/3
